### ISSUE TITLE
Default commands

### ISSUE THREAD

**Issue by Innectic** [ConduitMC/Conduit#12]
Shouldn't be much, mainly just a `/plugin` and `/version` command.

Something like:

/plugin: list all current plugins
/plugin disable <name>: disable a plugin
/plugin enable <name>: enable a plugin

`/version` will output the current API version, Conduit version, and Minecraft version

**Comment by Eldritch-Oliver** [comment]
Simple, clean, efficient. I like it.

Maybe also a `/plugin reload [plugin(s)|*]` to reload plugins.

**Comment by xIGBClutchIx** [comment]
Yep a plugin reload will be included. Right now we have /reload but will change that over.

**Comment by Eldritch-Oliver** [comment]
Excellent. Just wanted to make sure as it wasn't listed and it seemed like something that would be good to have.

**Comment by xIGBClutchIx** [comment]
Plugins command added in 86d350c24c0b60151888873950c37b3854a5710d
Version command added in 2d9b8eb2b848c81e4cfdb7217126f9986c0b769d
