### ISSUE TITLE
Setup jenkins for automated building

### ISSUE THREAD

**Issue by Innectic** [ConduitMC/Conduit#27]
Gotta get some automated builds going

**Comment by xIGBClutchIx** [comment]
Possibly use [Travis CI](https://travis-ci.org/) and [Github Package Registry](https://github.com/features/package-registry)?

Two pretty good services that are easy to use and will eliminate costs.

**Comment by xIGBClutchIx** [comment]
We went with Github Actions and a [Nexus](https://repo.conduit.systems/)
