### ISSUE TITLE
Support spaces in plugin names

### ISSUE THREAD

**Issue by Innectic** [ConduitMC/Conduit#47]
Support spaces in both the @PluginMeta decorator, and in commands such as /conduit plugins reload <name>

**Comment by preyest1300** [comment]
Hey! I would like to try to tackle this one! Can I?

**Comment by Innectic** [comment]
Feel free!

**Comment by Innectic** [comment]
Hey @preyest1300 - Just checking for an update on your progress with this feature.

**Comment by Innectic** [comment]
Reassigning as we have received no response.

**Comment by Innectic** [comment]
Completed.
