### ISSUE TITLE
TOML Configuration Format

### ISSUE THREAD

**Issue by Eldritch-Oliver** [ConduitMC/Conduit#60]
A really nice configuration format for plugin configs would be [TOML](https://toml.io/en/) because IMO it's nicer to use for configs than both YAML and JSON as it's significantly easier to explain to users and is similar to YAML in style but doesn't depend completely depend on indentation for nested objects.

**Comment by Innectic** [comment]
Added to 0.0.8 milestone

**Comment by Eldritch-Oliver** [comment]
Wonderful. Thanks! :smile:

**Comment by Innectic** [comment]
It has been implemented in #63.
